# 20-access-control.conf - access control
server:
    # Access control — default deny, permit homelab subnets and Tailscale pool
    access-control: 0.0.0.0/0 refuse
    access-control: ::0/0 refuse
    access-control: 127.0.0.0/8 allow
    access-control: ::1/128 allow

    # Local clients
    access-control: 192.168.0.0/16 allow

    # Tailscale concerns
    #
    # - Sharing resources to guests — their device keeps its home tailnet
    #   IP, use 100.64.0.0/10 to cover all Tailscale CGNAT space
    # - Consuming their resources — your devices use your 100.124.224.0/21,
    #   their ACLs need to permit that range
    #access-control: 100.124.224.0/21 allow
    access-control: 100.64.0.0/10 allow
